export const DB_URL = 'mongodb://127.0.0.1:27017/arch'
export const PORT = 5000
export const SECRET = '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'
export const SMTP_HOST = 'smtp.gmail.com'
export const SMTP_PORT = 587
export const SMTP_USER = 'alinkon0207@gmail.com'
export const SMTP_PASS =  'btet hlwp iarz zlmu'
export const EMAIL_FROM = 'alinkon0207@gmail.com'
export const EMAIL_TO = 'gusaktolik228@gmail.com'
